spring:
  main:
    web-application-type: none
tiki:
  search:
    index:
      productIndex: product_dev
    service:
      port: 58080
    relevant:
      similarity:
        bm25:
          k1: 1.2
          b: 0.75
          test: str
